networks:
  nifi_net:
    driver: bridge

volumes:
  nifi_data:
  mysql_data:

services:
  mysql:
    image: mysql:8
    container_name: storage
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nifi_demo
      MYSQL_USER: nifi_user
      MYSQL_PASSWORD: nifi_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - /mnt/shared_vol/data:/mnt/shared
    networks:
      - nifi_net
    ports:
      - "3306:3306"

  nifi:
    image: apache/nifi:latest
    container_name: ingest
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      NIFI_WEB_HTTPS_PORT: ""
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin123
    ports:
      - "8080:8080"
    volumes:
      - /mnt/shared_vol/data:/mnt/shared
    networks:
      - nifi_net
    restart: unless-stopped
