networks:
  nifi_net:
    driver: bridge

volumes:
  nifi_data:
  mysql_data:

services:
  mysql:
    image: mysql:8
    container_name: storage
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nifi_demo
      MYSQL_USER: nifi_user
      MYSQL_PASSWORD: nifi_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - /mnt/shared_vol/data:/mnt/shared
    networks:
      - nifi_net
    ports:
      - "3306:3306"

  nifi:
    build:
      context: ./nifi
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    container_name: ingest
    ports:
      - "8443:8443"
    volumes:
      - /mnt/shared_vol/data:/mnt/shared
    networks:
      - nifi_net
    restart: unless-stopped